name: python
version: 4.0.5
schema: 1
scm: github.com/pubnub/python
changelog:
  - version: v4.0.5
    date:
    changes:
      - type: improvement
        text: new pubnub domain
      - type: improvement
        text: native demo app
      - type: improvement
        text: fixed HTTPAdapter config
      - type: improvement
        text: add a new Python 3.6.0 config to travis builds
      - type: improvement
        text: fix blocking Ctrl+C bug
  - version: v4.0.4
    date:
    changes:
      - type: improvement
        text: Add reconnection managers
  - version: v4.0.3
    date:
    changes:
      - type: improvement
        text: do not strip plus sign when encoding message.
  - version: v4.0.2
    date:
    changes:
      - type: improvement
        text: Adjusting maximum pool size for requests installations
      - type: improvement
        text: Adding Publsher UUID
  - version: v4.0.1
    date:
    changes:
      - type: improvement
        text: Fixing up packaging configuration for py3
  - version: v4.0.0
    date:
    changes:
      - type: improvement
        text: Initial Release
features:
  access:
    - ACCESS-GRANT
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-ASYNC
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-PUBLISHER-UUID
