name: python
version: 3.8.2
schema: 1
scm: github.com/pubnub/python
changelog:
  - version: v3.8.2
    date: 
    changes:
      - type: improvement
        text: Increasing maximum pool of connections and adjusting cryptodome package dependency.
  - version: v3.8.1
    changes:
      - type: bug
        text: Fixing bug with state setting and subscribe confirmation.
  - version: v3.8.0
    changes:
      - type: feature
        text: Mobile Gateway Functions.
      - type: feature
        text: Here Now for channel groups.
      - type: feature
        text: no-rep, store and fire().
  - version: v3.7.7
    changes:
      - type: improvement
        text: Adding .stop() method for base python async operations to exit the listener.
  - version: v3.7.6
    changes:
      - type: bug
        text: fixed issues in receiving gzipped response for twisted.
      - type: bug
        text: fix for non reporting of dns lookup failure.
      - type: bug
        text: fix in time method.
  - version: v3.7.5
    changes:
      - type: improvement
        text: increased timeout to 15 sec.
  - version: v3.7.4
    changes:
      - type: bug
        text: added state and here_now.
      - type: feature
        text: added presence heartbeat support.
  - version: v3.7.2
    changes:
      - type: bug
        text: fix for decryption bug in history API.
      - type: improvement
        text: module name changed to pubnub ( it was Pubnub earlier ), developers need to do from pubnub import Pubnub, instead of from Pubnub import Pubnub now.
      - type: bug
        text: fixed method arguments bug for presence API.
      - type: improvement
        text: subscribe_sync removed.
      - type: bug
        text: fix for issue where error callback not invoked for presence.
      - type: feature
        text: added state support in subscribe and here now.
      - type: bug
        text: fix for grant API with python 3.
      - type: feature
        text: added include_token option to history.
  - version: v3.7.0
    changes:
      - type: feature
        text: Channel Groups functionality.
      - type: improvement
        text: Added Python Echo Server example.
      - type: bug
        text: Added missing timeout keyword arg.
  - version: v3.5.3
    changes:
      - type: bug
        text: Added patch to handle quick net calls in Azure environments.
      - type: bug
        text: Presence fixes.
      - type: bug
        text: added daemon flag.
  - version: v3.5.2
    changes:
      - type: feature
        text: Added pnsdk URL param to each request.
      - type: improvement
        text: Added grant/revoke/audit examples to README.
      - type: bug
        text: Fixed erroneous "Connected" error condition in console.
      - type: improvement
        text: Can now pass init vars via the CL on console.
      - type: bug
        text: Fixed UI issue of bracket color on console.
      - type: improvement
        text: Enable subscribing to "-pnpres" channel on console.
  - version: v3.5.1
    changes:
      - type: feature
        text: Added subscribe_sync method.
      - type: improvement
        text: renamed pres_uuid argument for Pubnub constructor to uuid.
  - version: v3.5.0
    changes:
      - type: feature
        text: Async subscribe allows for MX, unsubscribe calls.
      - type: improvement
        text: New method signatures -- be sure to check migration doc if upgrading.
features:
  access:
    - GRANT
  channel-groups:
    - ADD-CHANNELS
    - REMOVE-CHANNELS
    - LIST-GROUPS
    - LIST-CHANNELS-IN-GROUP
  push:
    - ADD-DEVICE-TO-CHANNELS
    - REMOVE-DEVICE-FROM-CHANNELS
    - LIST-CHANNELS-FROM-DEVICE
    - REMOVE-DEVICE
  presence:
    - HERE-NOW
    - WHERE-NOW
    - SET-STATE
    - GET-STATE
    - HEARTBEAT
  publish:
   - STORE-FLAG
   - FIRE
   - REPLICATION-FLAG
