language: python
dist: xenial
os: linux

install:
  - bash scripts/install.sh


stages:
  - name: "test"
    if: |
      type != pull_request \
      AND tag IS blank
  - name: "code coverage"
    if: |
      type == pull_request

jobs:
  include:
    - stage: "test"
      name: 'Python 2.7'
      python: '2.7'
      script: python scripts/run-tests.py
    - name: 'Python 3.4'
      python: '3.4'
      script: python scripts/run-tests.py
    - name: 'Python 3.5'
      python: '3.5'
      script: python scripts/run-tests.py
    - name: 'Python 3.6'
      python: '3.6'
      script: python scripts/run-tests.py
    - name: 'Python PyPi'
      python: 'pypy'
      script: python scripts/run-tests.py
    - stage: "code coverage"
      name: 'Test & Code coverage'
      python: '3.6'
      script: python scripts/run-tests.py
      after_success:
        - python-codacy-coverage -r coverage.xml
