language: python
sudo: false
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

before_install:
  - pip install -r dev-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install twisted tornado pyopenssl; fi

install:
  python setup.py install


script: ./run-tests.sh
